# Generated by Django 6.0 on 2025-12-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_roomreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_number',
            field=models.IntegerField(),
        ),
    ]
